default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: spectrum-reg_development

test:
  <<: *default
  database: spectrum-reg_test

production:
  url: <%= ENV['DATABASE_URL'] %>
